name: pokeapi_client
description: PokeApi client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.1.0
